
server:
  port: 8080
  #???????
  servlet:
    context-path: /SpringBootConfig # 加了这行就是需要通过该地址才能访问到该服务的方法
  tomcat:     # tomcat相关的配置
    accept-count: 100
    max-connections: 10
#spring:
#  profiles:
#    active: